apiVersion: v1
kind: Service
metadata:
  name: {{ include "book-project.fullname" . }}
  labels:
    {{- include "book-project.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}     # 8080
      targetPort: {{ .Values.service.port }}  # 8080
      protocol: TCP
  selector:
    {{- include "book-project.selectorLabels" . | nindent 4 }}
